DROP DATABASE IF EXISTS Pollster;

CREATE DATABASE Pollster;

USE Pollster;

DROP TABLE IF EXISTS Setup;

CREATE TABLE Setup (
  id INT,
  today TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS Elections;

CREATE TABLE Elections (
  id INT AUTO_INCREMENT NOT NULL,
  date DATETIME NOT NULL,
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
  id INT AUTO_INCREMENT NOT NULL,
  firstName VARCHAR(15) NOT NULL,
  lastName VARCHAR(15) NOT NULL,
  email VARCHAR(30) NOT NULL,
  mobile VARCHAR(15) NOT NULL,
  party VARCHAR(15),
  password VARCHAR(20) NOT NULL,
  PRIMARY KEY(id)
);

CREATE TABLE UsersPreferences (
  id INT AUTO_INCREMENT NOT NULL,
  userID INT NOT NULL,
  colorScheme VARCHAR(20) NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(userID)
    REFERENCES Users(id)
    ON DELETE CASCADE
);

-- DROP TABLE IF EXISTS Users_1;

-- CREATE TABLE Users_1 (
--   id INT AUTO_INCREMENT NOT NULL,
--   firstName VARCHAR(100) NOT NULL,
--   lastName VARCHAR(100) NOT NULL,
--   email VARCHAR(20) NOT NULL,
--   mobile VARCHAR(15) NOT NULL,
--   PRIMARY KEY(id)
-- );

-- DROP TABLE IF EXISTS Users_2;

-- CREATE TABLE Users_2 (
--   id INT AUTO_INCREMENT NOT NULL,
--   firstName VARCHAR(100) NOT NULL,
--   lastName VARCHAR(100) NOT NULL,
--   email VARCHAR(20) NOT NULL,
--   mobile VARCHAR(15) NOT NULL,
--   PRIMARY KEY(id)
-- );


