DROP DATABASE IF EXISTS Pollster;

CREATE DATABASE Pollster;

USE Pollster;

DROP TABLE IF EXISTS Setup;

CREATE TABLE Setup (
  id INT,
  today TIMESTAMP
    ON UPDATE CURRENT_TIMESTAMP
    DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO Setup(id) VALUE (1);

DROP TABLE IF EXISTS Elections;

CREATE TABLE Elections (
  id INT AUTO_INCREMENT NOT NULL,
  date DATETIME NOT NULL,
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS Users;

CREATE TABLE Users (
  id INT AUTO_INCREMENT NOT NULL,
  firstName VARCHAR(70) NOT NULL,
  lastName VARCHAR(70) NOT NULL,
  email VARCHAR(70) NOT NULL,
  mobile VARCHAR(70) NOT NULL,
  password VARCHAR(70) NOT NULL,
  private_key VARCHAR(70) NOT NULL,
  public_key VARCHAR(70) NOT NULL,
  CONSTRAINT Users_unique UNIQUE (email, mobile),
  PRIMARY KEY(id)
);

DROP TABLE IF EXISTS UserInfo;

CREATE TABLE UserInfo (
  id INT AUTO_INCREMENT NOT NULL,
  user_id INT NOT NULL,
  address1 VARCHAR(70) NOT NULL,
  address2 VARCHAR(70),
  city VARCHAR(70) NOT NULL,
  state VARCHAR(70) NOT NULL,
  zipcode VARCHAR(70) NOT NULL,
  party VARCHAR(70),
  PRIMARY KEY(id),
  FOREIGN KEY(user_id) REFERENCES Users(id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

DROP TABLE IF EXISTS UserBallots;

CREATE TABLE UserBallots (
  id INT AUTO_INCREMENT NOT NULL,
  user_id INT NOT NULL,
  US_Presidential_Election_11_03_2020 VARCHAR(200) NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(user_id) REFERENCES Users(id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);
DROP TABLE IF EXISTS UserBallots;

CREATE TABLE UserBlocks (
  id INT AUTO_INCREMENT NOT NULL,
  user_id INT NOT NULL,
  US_Presidential_Election_11_03_2020 VARCHAR(200) NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(user_id) REFERENCES Users(id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);
CREATE TABLE BlockChain (
  id INT AUTO_INCREMENT NOT NULL,
  election_id INT NOT NULL,
  US_Presidential_Election_11_03_2020 VARCHAR(200) NOT NULL,
  PRIMARY KEY(id),
  FOREIGN KEY(election_id) REFERENCES User(id)
    ON DELETE CASCADE
    ON UPDATE RESTRICT
);

-- DROP TABLE IF EXISTS Users_1;

-- CREATE TABLE Users_1 (
--   id INT AUTO_INCREMENT NOT NULL,
--   firstName VARCHAR(100) NOT NULL,
--   lastName VARCHAR(100) NOT NULL,
--   email VARCHAR(20) NOT NULL,
--   mobile VARCHAR(15) NOT NULL,
--   PRIMARY KEY(id)
-- );

-- DROP TABLE IF EXISTS Users_2;

-- CREATE TABLE Users_2 (
--   id INT AUTO_INCREMENT NOT NULL,
--   firstName VARCHAR(100) NOT NULL,
--   lastName VARCHAR(100) NOT NULL,
--   email VARCHAR(20) NOT NULL,
--   mobile VARCHAR(15) NOT NULL,
--   PRIMARY KEY(id)
-- );


